# This section of values is for 1Password Connect API and Sync Configuration
connect:
  connect:
    replicas: 1
    api:
      serviceMonitor:
        enabled: true
    serviceType: LoadBalancer
    credentialsName: op-credentials
    credentialsKey: 1password-credentials.json
    credentials:
    credentials_base64:  

  operator:
    autoRestart: true
    token:
      name: onepassword-token
      key: token
      value:  