kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.12.0@sha256:5c1f8d671607d4c73a9fc373f7165cbc3dfd95b1f5871f4350c8b808bf3c5495
    repository: ghcr.io/mrkhachaturov/kamaji
