kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.15.0@sha256:872a3ea55fd45dc62878d54b14dd001dbe5ca202b397b00069778ef6602ea8ba
    repository: ghcr.io/mrkhachaturov/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
