kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: latest@sha256:fdcdd74f9acb0448f42069dc4ae6cd65e57e86db78f82453dba77754c5c3c1c6
    repository: ghcr.io/mrkhachaturov/kamaji
