kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.15.0@sha256:a0cb773b125862907e3598c79c212f39462b92f35f88cbf8a2c23299f9b2682d
    repository: ghcr.io/mrkhachaturov/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
